In [60]:
import numpy as np

In [61]:
'''
1. 선형대수
1.1. Vector and Matrix
'''

'''행렬 곱 (b)'''
np.random.seed(1)
n = 4
p = 3
m = 5
A = np.random.normal(size=(n, p))
B = np.random.normal(size=(p, m))
print(A @ B)
print('\n')
print('shape:', (A @ B).shape)

[[-0.46287612 -0.91506476  1.00928553 -0.7521667  -0.91546789]
 [-2.48880776 -0.7078998  -2.78548113  1.80129071  1.4584993 ]
 [ 0.39331724 -0.54192061  1.82197957 -1.29944023 -1.21143314]
 [-3.06052621 -0.87771621 -1.28647978  0.07363186  1.96987927]]


shape: (4, 5)


In [62]:
'''행렬 전치 (c)'''
np.random.seed(1)
n = 4
p = 3
m = 5
A = np.random.normal(size=(n, p))
B = np.random.normal(size=(p, m))
print((A @ B).T)
print('\n')
print(B.T @ A.T)
print('\n')
print(((A @ B).T == B.T @ A.T).all())

[[-0.46287612 -2.48880776  0.39331724 -3.06052621]
 [-0.91506476 -0.7078998  -0.54192061 -0.87771621]
 [ 1.00928553 -2.78548113  1.82197957 -1.28647978]
 [-0.7521667   1.80129071 -1.29944023  0.07363186]
 [-0.91546789  1.4584993  -1.21143314  1.96987927]]


[[-0.46287612 -2.48880776  0.39331724 -3.06052621]
 [-0.91506476 -0.7078998  -0.54192061 -0.87771621]
 [ 1.00928553 -2.78548113  1.82197957 -1.28647978]
 [-0.7521667   1.80129071 -1.29944023  0.07363186]
 [-0.91546789  1.4584993  -1.21143314  1.96987927]]


True


In [63]:
'''대각합 (b)'''
np.random.seed(1)
n = 4
p = 3
A = np.random.normal(size=(n, p))
B = np.random.normal(size=(p, n))
print(np.sum(np.diag(A @ B)))
print('\n')
print(np.sum(np.diag(B @ A)))

-0.49423632689484126


-0.49423632689484087


In [64]:
np.random.seed(1)
n = 4
p = 3
A = np.random.normal(size=(n, p))
B = np.random.normal(size=(n, p))
print(np.sum(np.diag(A + B)))
print('\n')
print(np.sum(np.diag(A)) + np.sum(np.diag(B)))

1.2133275002681543


1.2133275002681545


In [65]:
'''역행렬 (b)'''
np.random.seed(1)
p = 4
A = np.random.uniform(low=0.5, high=1.5, size=(p, p))
B = np.random.uniform(low=0.5, high=1.5, size=(p, p))
print(np.linalg.inv(A @ B))
print('\n')
print(np.linalg.inv(B) @ np.linalg.inv(A))

[[  -4.79118007  -56.84101235   50.93404072   -8.53199152]
 [  -5.75414501    9.34768015   -4.96343309    3.84061802]
 [  29.94410713  133.92495846 -121.32157933    4.84337546]
 [  -8.2686773   -48.33756767   39.2900596     0.72449223]]


[[  -4.79118007  -56.84101235   50.93404072   -8.53199152]
 [  -5.75414501    9.34768015   -4.96343309    3.84061802]
 [  29.94410713  133.92495846 -121.32157933    4.84337546]
 [  -8.2686773   -48.33756767   39.2900596     0.72449223]]


In [66]:
print(np.linalg.inv(A.T))
print('\n')
print(np.linalg.inv(A).T)

[[  2.91661188  -0.18236168  -1.55794075  -0.83868998]
 [  9.77502647  -8.90697436 -12.90359114  10.41806888]
 [ -8.79700163   7.1250794   13.38403112  -9.12515763]
 [ -0.15301008  -0.65536259  -3.16305932   3.14328516]]


[[  2.91661188  -0.18236168  -1.55794075  -0.83868998]
 [  9.77502647  -8.90697436 -12.90359114  10.41806888]
 [ -8.79700163   7.1250794   13.38403112  -9.12515763]
 [ -0.15301008  -0.65536259  -3.16305932   3.14328516]]


In [67]:
'''
1.2. Linear space
'''

'''선형 변환 (b)'''
x = np.array([[1], 
              [2], 
              [3]])
E_pi = np.array([[0, 0, 1], 
                 [1, 0, 0],
                 [0, 1, 0]])
print(E_pi @ x)

[[3]
 [1]
 [2]]


In [68]:
'''내적 (c)'''
np.random.seed(1)
p = 4
x = np.random.normal(size=(p, 1))
y = np.random.normal(size=(p, 1))
print('inner product:', x.T @ y)

# symmetry
print(y.T @ x)

# linearity
print('\n')
print((3 * y).T @ x)
print(3 * (y.T @ x))

print('\n')
z = np.random.normal(size=(p, 1))
print((x+y).T @ z)
print((x.T @ z) + (y.T @ z))

inner product: [[2.70889276]]
[[2.70889276]]


[[8.12667829]]
[[8.12667829]]


[[7.07833672]]
[[7.07833672]]


In [69]:
'''사영 (b)'''
np.random.seed(1)
X = np.random.normal(size=(n, p))
y = np.random.normal(size=(n, 1))
H = X @ np.linalg.inv(X.T @ X) @ X.T
y_hat = H @ y
print((y - y_hat).T @ y_hat)
print('orthogonal:', ((y - y_hat).T @ y_hat)[0][0] < 1e-8)

[[-3.27451596e-15]]
orthogonal: True


In [70]:
'''고유값 분해 (c)'''
np.random.seed(1)
# symmetric matrix
p = 3
A = np.random.uniform(low=1.5, high=2.5, size=(p, p)) 
B = A + A.T - np.diag(np.diag(A))
print('B:\n', B)
eigvalues, eigvectors = np.linalg.eig(B)
print('eigen values:', eigvalues)

print('\n')
# inner product
print(eigvectors[:, 0].T @ eigvectors[:, 0])
print(eigvectors[:, 1].T @ eigvectors[:, 1])
print(eigvectors[:, 2].T @ eigvectors[:, 2])

print('\n')
print(eigvectors[:, 0].T @ eigvectors[:, 1])
print(eigvectors[:, 0].T @ eigvectors[:, 2])
print(eigvectors[:, 1].T @ eigvectors[:, 2])

print('\n')
B_tmp = np.zeros_like(B)
for i in range(p):
    B_tmp += eigvalues[i] * (eigvectors[:, [i]] @ eigvectors[:, [i]].T)
print('B_tmp:\n', B_tmp)

B:
 [[1.917022   4.02265707 3.18637459]
 [4.02265707 1.64675589 3.43789932]
 [3.18637459 3.43789932 1.89676747]]
eigen values: [ 8.92592615 -2.28754391 -1.17783686]


1.0
0.9999999999999999
1.0000000000000002


1.6653345369377348e-16
-3.3306690738754696e-16
1.4155343563970746e-15


B_tmp:
 [[1.917022   4.02265707 3.18637459]
 [4.02265707 1.64675589 3.43789932]
 [3.18637459 3.43789932 1.89676747]]


In [71]:
'''특이값 분해 (b)'''
np.random.seed(1)
n = 5
p = 3
A = np.random.normal(size=(n, p))
U, D, V = np.linalg.svd(A, full_matrices = True)

print('A:\n', A)
print('\n')
print('U:\n', U)
print('\n')
print('D:\n', D)
print('\n')
print('V transposed:\n', V)
print('\n')
print('svd:\n', U[:, :p] @ np.diag(D) @ V) 

A:
 [[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391 ]
 [-0.24937038  1.46210794 -2.06014071]
 [-0.3224172  -0.38405435  1.13376944]]


U:
 [[-0.13417288  0.69886467  0.2744805   0.6350646   0.12222611]
 [ 0.6674267   0.0631622   0.67001339 -0.25492677  0.19143287]
 [-0.33162973  0.57280293 -0.05698611 -0.7166491   0.21233272]
 [ 0.60841133  0.26943082 -0.68545514  0.07317699  0.28642463]
 [-0.23747973 -0.32695955  0.05144271  0.11298007  0.90625051]]


D:
 [3.95920504 2.46910273 0.65100495]


V transposed:
 [[-0.40105391  0.47809706 -0.78139552]
 [ 0.85257252 -0.11720381 -0.50929693]
 [-0.3350759  -0.87045188 -0.36060736]]


svd:
 [[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391 ]
 [-0.24937038  1.46210794 -2.06014071]
 [-0.3224172  -0.38405435  1.13376944]]


In [72]:
'''
1.4. Matrix calculus
'''

'''행렬식 (a)'''
np.random.seed(1)
p = 4
A = np.random.uniform(low=-1.5, high=1.5, size=(p, p)) 
B = np.random.uniform(low=-1.5, high=1.5, size=(p, p)) 

# properties
print(np.linalg.det(A))
print(np.linalg.det(A.T))
print('\n')

print(np.linalg.det(2 * A))
print((2 ** p) * np.linalg.det(A))
print('\n')

print(np.linalg.det(A @ B))
print(np.linalg.det(A) * np.linalg.det(B))

-0.7863673345700123
-0.7863673345700116


-12.581877353120195
-12.581877353120197


1.788205949868992
1.7882059498689968


In [73]:
'''QR 분해 (a)'''
A = np.array([[1, 0, 1],
              [0, -3, 1],
              [2, 1, 3]])
Q, R = np.linalg.qr(A)
print('Q:\n', Q)
print('R:\n', R)

Q:
 [[-0.4472136  -0.13187609 -0.88465174]
 [-0.         -0.98907071  0.14744196]
 [-0.89442719  0.06593805  0.44232587]]
R:
 [[-2.23606798 -0.89442719 -3.13049517]
 [ 0.          3.03315018 -0.92313266]
 [ 0.          0.          0.58976782]]


In [74]:
'''LU 분해 (a)'''
A = np.array([[1, 0, 1],
              [0, -3, 1],
              [2, 1, 3]])
import scipy.linalg   
P, L, U = scipy.linalg.lu(A)
print('L:\n', L)
print('U:\n', U)

L:
 [[1.         0.         0.        ]
 [0.         1.         0.        ]
 [0.5        0.16666667 1.        ]]
U:
 [[ 2.          1.          3.        ]
 [ 0.         -3.          1.        ]
 [ 0.          0.         -0.66666667]]


In [75]:
# A = np.array([[1, 0, 1],
#               [0, -3, 1],
#               [2, 1, 3]])
# b = np.array([[6], [7], [15]])
# print(np.linalg.inv(A) @ b)

In [76]:
'''촐레스키 분해 (a)'''
np.random.seed(1)
A = np.random.uniform(low=1.5, high=3.5, size=(3, 3)) + np.diag([1., 1., 1.])
L = np.linalg.cholesky(A)
print('A:\n', A)
print('L:\n', L)
print('cholesky:\n', L @ L.T)

A:
 [[3.33404401 2.94064899 1.50022875]
 [2.10466515 2.79351178 1.68467719]
 [1.87252042 2.19112145 3.29353495]]
L:
 [[1.82593647 0.         0.        ]
 [1.15264971 1.21033484 0.        ]
 [1.02551236 0.83370725 1.24370076]]
cholesky:
 [[3.33404401 2.10466515 1.87252042]
 [2.10466515 2.79351178 2.19112145]
 [1.87252042 2.19112145 3.29353495]]


In [77]:
'''
2. 제약조건이 없는 문제의 최적화 알고리즘 (Unconstrained problem and optimization)

poisson regression model
problem: unconstrained minimization of negative log-likelihood

y_i ~ Poisson(E(y_i|x_i)) = Poisson(exp(x_i @ beta))
'''
np.random.seed(1)
n = 1000
p = 3
true_beta = np.array([[1.5], [0.5], [1.0]])
print('true beta:\n', true_beta)

X = np.random.normal(loc=0, scale=0.2, size=(n, p-1)) # 상수항 이외의 predictors
X = np.hstack((np.ones((n, 1)), X)) # 상수항
print('design matrix:\n', X[:5, :])

parm = np.exp(X @ true_beta)
print('true poisson parameters\n', parm[:5, :])

y = np.random.poisson(parm) # 모수값을 계산하고 poisson 분포를 이용해 y를 생성
print('response variable:\n', y[:5, :])

learning_rate = 0.0001 # eta

true beta:
 [[1.5]
 [0.5]
 [1. ]]
design matrix:
 [[ 1.          0.32486907 -0.12235128]
 [ 1.         -0.10563435 -0.21459372]
 [ 1.          0.17308153 -0.46030774]
 [ 1.          0.34896235 -0.15224138]
 [ 1.          0.06380782 -0.04987408]]
true poisson parameters
 [[4.66497863]
 [3.43009892]
 [3.08401717]
 [4.58247753]
 [4.40187169]]
response variable:
 [[5]
 [3]
 [5]
 [2]
 [5]]


In [78]:
'''1. 경사하강법'''
beta = np.array([.5, .5, .5]).reshape((p, 1)) # initial beta
# 1차 미분
grad = -np.sum(y * X - np.exp(X @ beta) * X, axis=0).reshape((p, 1))
print('gradient:\n', grad)
print('shape:', grad.shape)

gradient:
 [[-2895.16823845]
 [  -87.51803178]
 [ -158.74131746]]
shape: (3, 1)


In [79]:
beta = np.ones((p, 1)) # initial beta
for i in range(500):
    grad = -np.sum(y * X - np.exp(X @ beta) * X, axis=0).reshape((p, 1))

    # beta update
    beta_new = beta - learning_rate * grad
    
    # stopping rule
    if np.sum(np.abs(beta_new - beta)) < 1e-8:
        beta = beta_new
        print('Iteration {} beta:'.format(i+1))
        print(beta, '\n')
        break
    else:
        beta = beta_new
        print('Iteration {} beta:'.format(i+1))
        print(beta, '\n')

Iteration 1 beta:
[[1.17080498]
 [1.00004739]
 [1.00746866]] 

Iteration 2 beta:
[[1.28817266]
 [0.99762024]
 [1.01249645]] 

Iteration 3 beta:
[[1.36319061]
 [0.99326979]
 [1.01557887]] 

Iteration 4 beta:
[[1.40846948]
 [0.98761715]
 [1.01728997]] 

Iteration 5 beta:
[[1.43475216]
 [0.98118739]
 [1.018123  ]] 

Iteration 6 beta:
[[1.44967534]
 [0.97435059]
 [1.01843019]] 

Iteration 7 beta:
[[1.45808371]
 [0.96733911]
 [1.0184356 ]] 

Iteration 8 beta:
[[1.46284665]
 [0.9602887 ]
 [1.01827215]] 

Iteration 9 beta:
[[1.46559721]
 [0.95327508]
 [1.01801561]] 

Iteration 10 beta:
[[1.46724413]
 [0.94633908]
 [1.01770821]] 

Iteration 11 beta:
[[1.46828692]
 [0.93950195]
 [1.01737323]] 

Iteration 12 beta:
[[1.46899828]
 [0.93277421]
 [1.01702341]] 

Iteration 13 beta:
[[1.46952659]
 [0.92616053]
 [1.01666575]] 

Iteration 14 beta:
[[1.46995245]
 [0.91966244]
 [1.0163041 ]] 

Iteration 15 beta:
[[1.47031965]
 [0.91327979]
 [1.01594058]] 

Iteration 16 beta:
[[1.47065197]
 [0.90701154]
 [

In [80]:
'''2. 뉴튼-랩슨법'''
beta = np.array([.5, .5, .5]).reshape((p, 1))

D1 = X[:, :, None] @ X[:, None, :]
print('shape of D1:', D1.shape)
D2 = np.exp(X @ beta)[:, :, None]
print('shape of D2:', D2.shape)

# 2차 미분
print('\n')
Hessian = -np.sum(-D2 * D1, axis=0)
print('Hessian:\n', Hessian)
print('shape of Hessian:', Hessian.shape)

shape of D1: (1000, 3, 3)
shape of D2: (1000, 1, 1)


Hessian:
 [[1675.83176155   45.76716564   41.26119256]
 [  45.76716564   68.68940526   -1.8078155 ]
 [  41.26119256   -1.8078155    68.37325968]]
shape of Hessian: (3, 3)


In [81]:
beta = np.ones((p, 1)) # initial beta
for i in range(500):
    # 1차와 2차 미분 계산
    grad = -np.sum(y * X - np.exp(X @ beta) * X, axis=0).reshape((p,1))
    
    D1 = X[:, :, None] @ X[:, None, :]
    D2 = np.exp(X @ beta)[:, :, None]
    Hessian = -np.sum(-D2 * D1, axis=0)
    
    # beta update
    beta_new = beta - np.linalg.inv(Hessian) @ grad
    
    # stopping rule
    if np.sum(np.abs(beta_new - beta)) < 1e-8:
        beta = beta_new
        print('Iteration {} beta:'.format(i+1))
        print(beta, '\n')
        break
    else:
        beta = beta_new
        print('Iteration {} beta:'.format(i+1))
        print(beta, '\n')

Iteration 1 beta:
[[1.63027478]
 [0.30714956]
 [0.96507126]] 

Iteration 2 beta:
[[1.49637062]
 [0.53367681]
 [0.97667225]] 

Iteration 3 beta:
[[1.48523165]
 [0.5675415 ]
 [0.97852502]] 

Iteration 4 beta:
[[1.4851458 ]
 [0.56789863]
 [0.97854663]] 

Iteration 5 beta:
[[1.4851458 ]
 [0.56789866]
 [0.97854663]] 

Iteration 6 beta:
[[1.4851458 ]
 [0.56789866]
 [0.97854663]] 

